title: Java Bootcamp 
description: 5 Weeks Bootcamp on Java
baseurl: "/java-bootcamp"
url: "https://gutsofdarkness.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "src"
    values:
      layout: "post"
  - scope:
      path: "extras"
    values:
      layout: "post"